// resuma-routes-fingerprint: 1d6ce5ff96ca2b4a
// Auto-generated by `resuma routes --generate`. Do not edit by hand.
use resuma::prelude::*;
use resuma::FlowPageRegistry;

pub struct PagesRegistry;

impl FlowPageRegistry for PagesRegistry {
fn routes(&self) -> &'static [(&'static str, &'static str)] {
&[
                    ("/", "index"),
                    ("/about", "about"),
                    ("/login", "login"),
                    ("/register", "register"),
                ]
}

fn layout_for(&self, pattern: &str) -> &'static [&'static str] {
match pattern {
                    "/" => &["/"],
                    "/about" => &["/"],
                    "/login" => &["/"],
                    "/register" => &["/"],
                    _ => &[],
}
}

fn render(&self, module: &str, req: FlowRequest) -> Option<View> {
match module {
            "index" => Some(super::index::page(req)),
            "about" => Some(super::about::page(req)),
            "login" => Some(super::login::page(req)),
            "register" => Some(super::register::page(req)),
            _ => None,
}
}
}
